# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luther9.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Luther Thompson
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website about my coding practices" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developer and Free Software User.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "lutheroto@gmail.com"
  behance:
  bitbucket: "luther9"
  dribbble:
  facebook:
  flickr:
  github: "luther9"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/luther-thompson-a4219a127" # Full URL
  pinterest:
  reddit: "luther9"
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/3574628/luther" # Full URL
  steam:
  tumblr:
  twitter:
  wordpress: "luther9"
  youtube: "lutheroto"

  # Scripts
  google_analytics: "UA-87907866-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
